# Docker Compose Override for Port Conflicts
# Save this as docker-compose.override.yml

version: '3.8'

services:
  # Main application with alternative port
  app:
    ports:
      - "${PORT:-5002}:5000"  # Use PORT env var or default to 5002
    environment:
      - PORT=5000  # Internal port stays 5000
    
  # Development application with different port
  app-dev:
    ports:
      - "${DEV_PORT:-5003}:5000"  # Use DEV_PORT env var or default to 5003
    environment:
      - PORT=5000  # Internal port stays 5000
    
  # PostgreSQL with alternative port if needed
  postgres:
    ports:
      - "${POSTGRES_PORT:-5433}:5432"  # Alternative port 5433
    
  # Redis with alternative port if needed
  redis:
    ports:
      - "${REDIS_PORT:-6380}:6379"  # Alternative port 6380
    
  # Nginx with alternative ports
  nginx:
    ports:
      - "${NGINX_PORT:-8080}:80"
      - "${NGINX_SSL_PORT:-8443}:443"
    
  # Monitoring services with alternative ports
  prometheus:
    ports:
      - "${PROMETHEUS_PORT:-9091}:9090"
  
  grafana:
    ports:
      - "${GRAFANA_PORT:-3001}:3000"
  
  elasticsearch:
    ports:
      - "${ELASTICSEARCH_PORT:-9201}:9200"
  
  kibana:
    ports:
      - "${KIBANA_PORT:-5602}:5601"
  
  locust:
    ports:
      - "${LOCUST_PORT:-8090}:8089"